#!/bin/bash
SSH=$1
if [ ! -z "$SSH_PRIVATE" ]; then
	echo "# Get SSH private key from env variable"
	echo $SSH_PRIVATE > ~/.ssh/id_rsa.tmp
	base64 -di ~/.ssh/id_rsa.tmp > ~/.ssh/id_rsa
 	chmod 600 ~/.ssh/id_rsa
	echo "# SSH Key added"
fi
